function c = colL(kind, n, r, q, lambda, mu)
% Column generated by the longitudinal potential basis function.
    Z = cyl(kind, n, q*r);
    dZ = q * dcyl(kind, n, q*r);
    ddZ = d2cyl_dr2(kind, n, r, q);

    c = [
        dZ;
        1i*n/r * Z;
        lambda/r*dZ + (lambda + 2*mu)*ddZ - lambda*n^2/r^2*Z;
        2i*n*mu/r * (dZ - Z/r)
    ];
end